spring:
  security:
    user:
      name: "user"
      password: "password"
  application:
    name:
      api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      excludedUrls:
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter
            - StripPrefix=0

        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path= /api/auth/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter
            - StripPrefix=0

        - id: item-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/items/**,/api/image/**
          filters:
            - AuthenticationFilter
            - StripPrefix=0

        - id: item_cart-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/item_carts/**,/api/carts/**,/api/specifications/**
          filters:
            - AuthenticationFilter
            - StripPrefix=0
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
